name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DISPLAY: :99
  WDM_GITHUBTOKEN: ${{ secrets.WDM_GITHUBTOKEN }}

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 11 ]

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Start Xvfb on Linux
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb :99 &
    - name: Run tests Maven
      run: mvn clean test -DsuiteFile=testngch.xml
